name: Monitor highlights

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  monitor-highlights:
    runs-on: ubuntu-latest
    steps:
      - name: Monitor PL
        run: curl -fsS "https://footyam.vercel.app/api/cron-monitor?league=PL"

      - name: Monitor La Liga
        run: curl -fsS "https://footyam.vercel.app/api/cron-monitor?league=PD"

      - name: Monitor Bundesliga
        run: curl -fsS "https://footyam.vercel.app/api/cron-monitor?league=BL1"

      - name: Monitor Serie A
        run: curl -fsS "https://footyam.vercel.app/api/cron-monitor?league=SA"

      - name: Monitor Ligue 1
        run: curl -fsS "https://footyam.vercel.app/api/cron-monitor?league=FL1"
